### ISSUE TITLE
espcoredump.py crashes when the host CPU is not idle (IDFGH-8988)

### ISSUE THREAD

**Issue by Andste82** [espressif/esp-coredump#1]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

Linux

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

None

### Development Kit.

none

### Power Supply used.

USB

### What is the expected behavior?

espcoredump.py should always return the same result if the same inputfiles and arguments are used.

### What is the actual behavior?

depending on the system load of the host system, the python script crashes at different program points.

### Steps to reproduce.

1. generate CPU load on you're development machine (building a huge project on all CPUs)
2. run python3 /esp-idf/components/espcoredump/espcoredump.py info_corefile  --print-mem --core-format raw --core core.dump firmware.elf

### Debug Logs.

```plain
example crash:
the program crashes in many different places, which indicates that the GDB communication is faulty!

Traceback (most recent call last):
  File "/esp-idf/components/espcoredump/espcoredump.py", line 350, in <module>
    temp_core_files = info_corefile()
  File "/esp-idf/components/espcoredump/espcoredump.py", line 200, in info_corefile
    threads, _ = gdb.get_thread_info()
  File "/esp-idf/components/espcoredump/corefile/gdb.py", line 114, in get_thread_info
    current_thread_id = result['current-thread-id']
TypeError: 'NoneType' object is not subscriptable
```

### More Information.

the problem can be easily reproduced under ubuntu 22.04 and windows 10.

it looks like pygdbmi has problems when the GDB does not react fast enough due to high system load.

**Comment by alekseiapa** [comment]
Greetings, @Andste82. We appreciate you reporting this problem. Please allow me to look at this.

**Comment by dobairoland** [comment]
This has been addressed in the linked commit.
