### ISSUE TITLE
Cannot find GDB (IDFGH-12412)

### ISSUE THREAD

**Issue by SukuWc** [espressif/esp-coredump#7]
## Install dependencies
```
pip install esp-coredump
```
## Copy the provided example to core.py
```
from esp_coredump import CoreDump

# Instantiate the coredump object
coredump = CoreDump(chip='esp32s3',core="./dump.bin", prog='./app.elf')
coredump.info_corefile()  #  print the info of the test app corefile
```

## Try to run the app
```
python3 core.py
```
## Result
```
===============================================================
==================== ESP32 CORE DUMP START ====================
GDB executable not found. Please install GDB or set up ESP-IDF to complete the action. Read more: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html
```

## Question
How can I install the esp specific gdb executables without installing the entire esp-idf framework?

## Workaround
- Step 1 copied the xtensa-esp-elf-gdb folder from esp-idf next to core.py
- Run the following command: export PATH="$(pwd)/xtensa-esp-elf-gdb/bin:$PATH"
- Then run python3 core.py and now it works
- Is there a nicer way to properly install the required esp specific GDB tools?

**Comment by igrr** [comment]
You  can find the releases here: https://github.com/espressif/binutils-gdb/releases

Installing the latest release should generally work, but if you'd like to find the specific GDB release used by IDF, you can find it in the docs: https://docs.espressif.com/projects/esp-idf/en/v5.2.1/esp32/api-guides/tools/idf-tools.html#xtensa-esp-elf-gdb.

**Comment by dobairoland** [comment]
Probably we need a better documentation on how to use this as a standalone tool.
